### ISSUE TITLE
Team 18 Phase 2 - Robber doesn't work

### ISSUE THREAD

**Issue by Harrismc** [cs340tabyu/CatanBugTracker#25]
Upon entering game 0 as Sam and rolling a seven on the initial roll, the robber modal failed to show. The turn button said I was robbing, but was enabled and when clicked ended my turn.

**Comment by colingm** [comment]
This happened to me but it didn't let me even click the button, the game was basically frozen and unplayable. I think this only happens if someone had to discard, otherwise it acted like harrismc explained.

![image](https://cloud.githubusercontent.com/assets/11670266/10778043/2fc5fb28-7ce7-11e5-82bd-c7d1e55a9fa1.png)
