### ISSUE TITLE
Team 3 Phase 3 - Tied for Longest Road Bug

### ISSUE THREAD

**Issue by shampto3** [cs340tabyu/CatanBugTracker#480]
Steps Taken:
- With one player, obtain the longest road
- With another player, tie the first player for the longest road (I even had another player tie for it)

Expected Results:
- When you tie for the longest road, the first player to obtain it keeps it until someone gets more roads.

Actual Results:
- When the first player got the longest road, it gave it to him
- When the second player tied for the longest road it took it away from the first player so no one had the longest road

<img width="537" alt="longest_road_error" src="https://cloud.githubusercontent.com/assets/8238593/11312454/706f9508-8f93-11e5-8ff4-7b36d537fd9e.png">

**Comment by sebrantley** [comment]
Not completely sure this is a bug. I guess it depends on the definition of "after a longest road is broken" when only implementing most roads as the criteria

From the Settlers of Catan Rules pdf
"Set the “Longest Road” card aside if—after a longest road is
broken—several players tie for the new longest road or no
one has a 5+ segment road. The “Longest Road” card comes
into play again when only 1 player has the longest road (of at
least 5 road pieces)."

**Comment by ramorris3** [comment]
What happens when another player breaks the tie later on by getting the most?

So like this:
- When the first player got the longest road, it gave it to him
- When the second player tied for the longest road it took it away from the first player so no one had the longest road
- When another player (first, second, or anyone else) got broke the tie by getting most roads again, is the longest road again put into play?
