### ISSUE TITLE
AI builds illegal road - TAs please update labels to reflect server issue not Team 16 issue

### ISSUE THREAD

**Issue by eric-nord** [cs340tabyu/CatanBugTracker#83]
- Illegal road building by AI WHITE - cannot build through another players Settlement
  ![image](https://cloud.githubusercontent.com/assets/2634204/10794044/e985a1e6-7d58-11e5-8e79-b31e37135b55.png)

Build order 
Player places Green settlement
WHITE AI places illegal road through green settlement

**Comment by Jeutnarg** [comment]
The AI is not handled by the client. There is no way to prevent the AI from making illegal moves on its own turn, only ways to prevent human-controlled players from making this illegal move. There is also no mechanism for removing a road, so it cannot be fixed afterwards. Furthermore, even if such a mechanism existed, there is no way to know for sure, based entirely on current state, that all such situations are actually illegal. In this situation it is unambiguous, but if that green settlement were connected to another green settlement, then it would be unclear as to the build order, which would be necessary to know in order to declare the move illegal.

**Comment by eric-nord** [comment]
You are right this is something we cannot resolve I'll update it with the TAs as the team and ask them to update the server. 
Build order was I place Green settlement then WHITE AI placed illegal road.
